name: Promote Gateway API Integrator charm

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        type: choice
        description: 'Origin Channel'
        options:
        - latest/edge
      destination-channel:
        type: choice
        description: 'Destination Channel'
        options:
        - latest/stable
      base-channel:
        type: choice
        description: 'Base Channel'
        options:
        - 24.04
        - 22.04
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  promote-charm:
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: ${{ github.event.inputs.origin-channel }}
      destination-channel: ${{ github.event.inputs.destination-channel }}
      base-channel: ${{ github.event.inputs.base-channel }}
      doc-automation-disabled: false
      working-directory: ./gateway-api-integrator
    secrets: inherit
